### ISSUE TITLE
some devices are missing from the 3D output

### ISSUE THREAD

**Issue by infrastation** [magnusmichaelson/rack3d#2]
The input is the "New York" sample location from demo.racktables.org:
![demo_dc_in](https://user-images.githubusercontent.com/900115/42324826-37e259fc-805c-11e8-86c6-90f212ffb0b7.png)

The output .obj file seems to have roughly half of the devices missing:
![demo_dc_out](https://user-images.githubusercontent.com/900115/42324829-3ac0d3a6-805c-11e8-835a-d88d13815c8b.png)

Could you check?

**Comment by magnusmichaelson** [comment]
it was this sql...
(o.objtype_id=4 OR objtype_id=8 OR objtype_id=9)

in this query...
"SELECT DISTINCT o.name AS objName, o.id AS objId, o.objtype_id AS objType FROM Object AS o INNER JOIN RackSpace AS r ON o.id = r.object_id WHERE (o.objtype_id=4 OR objtype_id=8 OR objtype_id=9) AND r.rack_id="+str(rackId)

i've removed it now and it should show all objects, not just servers, switches and patchpanels.

thanks for the feedback. :)
